**Task 2: 1D Practice** 
1. Access first element  
2. Access last element  
3. Slice array 

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])

In [5]:
print(arr[0])  #------> accessing first element
print(arr[-1]) #------>  accessing last element
print(arr[2:5]) #------> Slice array

10
50
[30 40 50]


**Task 3: 2D Practice** 
1. Access element  
2. Print row  
3. Print column 

In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [10]:
print(arr[1,2])  #------> Access element
print(arr[1])    #------> print row
print(arr[:,2])  #------> print column

6
[4 5 6]
[3 6 9]


**Task 4: 3D Practice** 
1. Access layer  
2. Access row inside layer  
3. Access single element 

In [11]:
arr = np.array([
    [[10, 20, 30],
     [40, 50, 60]],

    [[17, 18, 19],
     [10, 11, 12]]
])

In [14]:
arr.shape

(2, 2, 3)

In [19]:
print("Layer1:",arr[0])  #------>Access Layer  0
print("Layer2:",arr[1])  #------>Access Layer 1
print("row inside layer:",arr[0, 1])  #----> Access row inside layer

Layer1: [[10 20 30]
 [40 50 60]]
Layer2: [[17 18 19]
 [10 11 12]]
row inside layer: [40 50 60]


**Task 5: Slicing**
1. Extract sub-array  
2. Use step slicing  
3. Slice rows and columns 

In [20]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

In [21]:
print(arr[0:2, 0:3])   #------>Extract sub-array

[[10 20 30]
 [50 60 70]]


In [22]:
print(arr[:, ::2])  #------>Step Slicing

[[ 10  30]
 [ 50  70]
 [ 90 110]]


In [23]:
print(arr[1:3, 1:4])  #----->SLice rows and columns


[[ 60  70  80]
 [100 110 120]]


**Boolean Indexing** 
1. Filter values > 25  
2. Filter values between range  
3. Replace values conditionally 

In [24]:
arr = np.array([10, 20, 30, 40, 50])

In [25]:
print(arr[arr > 25])  #----->FIlters values > 25


[30 40 50]


In [28]:
print(arr[(arr > 10) & (arr < 50)]) #-----> Filter values between range

[20 30 40]


In [29]:
arr[arr > 30] = 100
print(arr)

[ 10  20  30 100 100]
