# Numpy Arithmetic Operations
Today’s session focused on performing fast and efficient mathematical operations using NumPy arrays. This is one of the core strengths of NumPy in data science and machine learning.

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [4]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]


# Numpy Built in function

In [6]:
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))
print(np.power(a, 2))
print(np.mod(a, b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[1 2 3]


# Scalar Operations

Operation with a single value

In [7]:
a = np.array([1, 2, 3])

In [8]:
print(a+10)
print(a-1)
print(a*10)
print(a/2)

[11 12 13]
[0 1 2]
[10 20 30]
[0.5 1.  1.5]


# 1. What is vectorization? 

Vectorization means performing operations on entire arrays at once without using explicit loops.
 Instead of processing element-by-element (like in normal Python), NumPy processes whole arrays in a single step.

# Without Vectorization (Using Loops)

In [9]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

result = []

for i in range(len(a)):
    result.append(a[i] + b[i])

print(result)

[6, 8, 10, 12]


###### Slower
###### More code
###### Not efficient

# With Vectorization (NumPy Way)

In [10]:
result = a + b
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


###### Faster
###### Cleaner
###### Efficient

# 2. Difference between list and NumPy operations 

| Feature              | Python List    | NumPy Array                    |
| -------------------- | ---------------- | --------------------------- |
| Operation Type       | Not element-wise | Element-wise                |
| Addition (`+`)       | Concatenation    | Mathematical addition       |
| Multiplication (`*`) | Repetition       | Element-wise multiplication |
| Speed                | Slower           | Faster (vectorized)         |
| Memory               | Less efficient   | More efficient              |
| Code Style           | Requires loops   | No loops needed             |
| Use Case             | General purpose  | Data science, ML            |


# 3. What are aggregation functions? 

In data analysis, aggregation functions are used to summarize a dataset into a single value.
sum()
mean()
median()
min()
max()
std()
var()
prod()
cumsum()
cumprod()
###### Summarize large datasets
###### Calculate totals (sum)
###### Find average values (mean)
###### Identify highest and lowest values (max, min)
###### Measure data spread (std, var)
###### Analyze trends and patterns
###### Data preprocessing for machine learning
###### Performance evaluation (e.g., marks, sales)
###### Statistical analysis
###### Quick insights for decision-making

# 4. What is axis? 

In NumPy, an axis refers to the direction along which operations are performed in an array.

In [11]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

Axis = 0 (Columns ⬇️)
Operation goes down the rows
Works column-wise

In [12]:
np.sum(a, axis=0)

array([5, 7, 9])

Axis = 1 (Rows ➡️)
Operation goes across columns
Works row-wise

In [13]:
np.sum(a, axis=1)

array([ 6, 15])

# 5. Why NumPy is faster? 

NumPy is much faster than regular Python lists because of how it handles data and computations internally.

#### Main Reasons

###### Vectorization (No Loops)


NumPy performs operations on entire arrays at once


Avoids slow Python loops

Faster execution 

###### Written in C (Low-Level Speed)


Core NumPy operations are implemented in C language


Closer to hardware → faster performance



###### Contiguous Memory Storage


Data is stored in continuous blocks of memory


Improves access speed and cache efficiency



###### Less Memory Usage


NumPy arrays use fixed data types


Python lists store extra metadata for each element


 More compact & efficient

###### Broadcasting


Performs operations between arrays of different shapes


No need for manual looping



###### SIMD Optimization


Uses Single Instruction, Multiple Data


Performs the same operation on multiple values simultaneously





