**Task 2: Reshape Practice** 
1. Convert 1D → 2D  
2. Convert 1D → 3D  
3. Try invalid reshape  

In [1]:
import numpy as np

In [2]:
#Convert 1D -> 2D
arr=np.array([5,2,3,6,4,5,9,8])

In [4]:
arr.size

8

In [5]:
#possible reshape (2,4) or (4,2)
print(arr.reshape(2,4))

[[5 2 3 6]
 [4 5 9 8]]


In [6]:
#Convert 1D -> 3D
print(arr.reshape(2,2,2))

[[[5 2]
  [3 6]]

 [[4 5]
  [9 8]]]


In [7]:
#try invalid shape
print(arr.reshape(3,2))

ValueError: cannot reshape array of size 8 into shape (3,2)

**Task 3: Flatten** 
1. Convert 2D → 1D  
2. Compare flatten vs ravel 

In [8]:
arr = np.array([[1,2,3],
                [5,6,7]])
print(arr)

[[1 2 3]
 [5 6 7]]


In [9]:
#Convert 2D-->1D
print(arr.flatten())

[1 2 3 5 6 7]


In [10]:
print(arr.ravel())

[1 2 3 5 6 7]


In [15]:
#compare flatten vs ravel
arr = np.array([[1,2,3],
                [4,5,6]])

flat = arr.flatten()
rav = arr.ravel()

flat[0] = 99
flat[3]=100
rav[1] = 88
rav[5]=32

print("Flatten:", flat)
print("Ravel:", rav)
print("Original array:\n", arr)

Flatten: [ 99   2   3 100   5   6]
Ravel: [ 1 88  3  4  5 32]
Original array:
 [[ 1 88  3]
 [ 4  5 32]]


**Task 4: Transpose**
1. Transpose matrix  
2. Verify rows    
columns 

In [17]:
arr = np.array([[3,4,5],
                [7,8,9]])
print(arr)
               

[[3 4 5]
 [7 8 9]]


In [19]:
# Transpose
t=arr.T
print(t)

[[3 7]
 [4 8]
 [5 9]]


In [21]:
#Verify rows and columns
print("Before Transpose:",arr.shape)
print("After Transpose:",t.shape)

Before Transpose: (2, 3)
After Transpose: (3, 2)


**Task 5: Stacking**
1. Vertical stack  
2. Horizontal stack  
3. Combine arrays 

In [22]:
arr1=np.array([2,4,5,6])
arr2=np.array([11,13,15,17])

In [23]:
#Vertical stack
np.vstack((arr1,arr2))

array([[ 2,  4,  5,  6],
       [11, 13, 15, 17]])

In [25]:
#Horizontal stack
np.hstack((arr1,arr2))

array([ 2,  4,  5,  6, 11, 13, 15, 17])

In [26]:
#Combine arrays
np.stack((arr1,arr2))

array([[ 2,  4,  5,  6],
       [11, 13, 15, 17]])

**Task 6: Splitting** 
1. Split array  
2. Split rows

In [27]:
# Split array
arr = np.array([1,2,3,4,5,6])
res = np.split(arr, 3)
print(res)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [28]:
# Split rows
arr2 = np.array([[1,2],
                 [3,4],
                 [5,6],
                 [7,8]])

res = np.vsplit(arr2, 2)
print(res)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
