In [1]:
import numpy as np

# 1. What is reshape?
 

Reshaping means changing the shape (dimensions) of an array without changing its data.

It helps in:
1. Preparing data for ML models
2. Converting between 1D, 2D, 3D arrays
3. Organizing data efficiently
###### Example: 
• 1D → 2D  
• 2D → 3D  

# 2.  Rule of reshape 

###### 1. Total Elements Must Match

The number of elements before and after reshaping must be the same.

👉 Formula:
Original size = New shape size

In [3]:

arr = np.array([1,2,3,4,5,6])  # size = 6

# Valid
arr.reshape(2,3)

# Invalid (2×2 = 4 ≠ 6)
#arr.reshape(2,2)

array([[1, 2, 3],
       [4, 5, 6]])

###### 2. Shape Must Be Compatible

The new shape must be a valid multiplication of dimensions.

✔ Examples for 6 elements:

(1,6)
(2,3)
(3,2)
(6,1)

##### 3. Use -1 for Automatic Dimension

NumPy can calculate one dimension automatically.

In [4]:
arr = np.array([1,2,3,4,5,6])

print(arr.reshape(2, -1))  # → (2,3)
print(arr.reshape(-1, 3))  # → (2,3)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


##### 4. Only One Unknown Dimension Allowed

In [6]:
#  Error
arr.reshape(-1, -1)

ValueError: can only specify one unknown dimension

##### 5. Reshape Does NOT Change Data
It only changes structure, not values.

In [7]:
arr = np.array([1,2,3,4])
print(arr.reshape(2,2))

[[1 2]
 [3 4]]


##### 6. Works Only with Continuous Data (View Concept)
reshape() usually returns a view, not a copy
If memory is not continuous, NumPy may create a copy internally
##### 7. Order Matters (Row-wise by Default)

NumPy fills data row-wise (C-order) by default.

In [8]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


# 3. Difference between flatten and ravel 
| Feature        | flatten()                       | ravel()                   |
| -------------- | ------------------------------- | ------------------------- |
| Returns        | Copy                            | View                      |
| Memory         | New memory                      | Same memory               |
| Speed          | Slower                          | Faster                    |
| Safe to modify | Yes                             | No (affects original)     |
| Use case       | When you want independent array | When you want performance |


In [10]:
#flatten()--Returns a copy of the original array
arr = np.array([[1,2],[3,4]])
flat = arr.flatten()

#flat[0] = 99

print(flat)  # [99  2  3  4]
print(arr)   # [[1 2]
             #  [3 4]]

[1 2 3 4]
[[1 2]
 [3 4]]


In [12]:
#travel()---Returns a view (reference) of the original array
arr = np.array([[1,2],[3,4]])
rav = arr.ravel()

#rav[0] = 99

print(rav)  # [99  2  3  4]
print(arr)  # [[99  2]
            #  [ 3  4]]

[1 2 3 4]
[[1 2]
 [3 4]]


# 4. What is transpose? 

Transpose means converting rows into columns and columns into rows.

In [13]:


arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [14]:
print(arr.transpose())  #Rows became columns & Columns became rows

[[1 4]
 [2 5]
 [3 6]]


1. Transpose = swap rows & columns
2. Shape changes (m, n) → (n, m)
3. Use .T or transpose()
4. Useful in ML & matrix math

# 5. What is stacking? 

Stacking means joining multiple arrays together by creating a new axis (dimension).
Stack = combine arrays one above another or side by side, but with an extra dimension.

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

res = np.stack((a, b))
print(res)

[[1 2 3]
 [4 5 6]]


# Types of Stacking
###  1. stack() (general)

In [16]:

np.stack((a, b), axis=0)  # row wise stacking

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.stack((a, b), axis=1) #column wise stacking

array([[1, 4],
       [2, 5],
       [3, 6]])

### 2. vstack() (vertical stack)

In [18]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

### 3. hstack() (horizontal stack)

In [19]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])