In [16]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings('ignore')

# **Task 2: Dataset Creation** 
1. Create Pass/Fail dataset  
2. Create Disease dataset  
3. Create Spam dataset 

In [35]:
#Create Pass/Fail dataset
pass_fail = {
    'Study_Hours': [2,3,4,5,6,7,8,9],
    'Result': [0,0,0,1,1,1,1,1]
}

df=pd.DataFrame(pass_fail)
df


,Study_Hours,Result
0,2,0
1,3,0
2,4,0
3,5,1
4,6,1
5,7,1
6,8,1
7,9,1


In [6]:
#Create Disease dataset
disease_data = {
    'Age': [20, 25, 30, 35, 40, 45, 50, 55, 60, 65],
    'Sugar_Level': [80, 90, 95, 100, 120, 130, 140, 150, 160, 180],
    'Disease': [0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
}

df1 = pd.DataFrame(disease_data)
df1

,Age,Sugar_Level,Disease
0,20,80,0
1,25,90,0
2,30,95,0
3,35,100,0
4,40,120,1
5,45,130,1
6,50,140,1
7,55,150,1
8,60,160,1
9,65,180,1


In [7]:
#Create spam dataset
spam_data = {
    'Email_Length': [50, 75, 100, 120, 60, 150, 80, 180, 90, 70],
    'Contains_Link': [0, 0, 1, 1, 0, 1, 0, 1, 1, 0],
    'Spam': [0, 0, 1, 1, 0, 1, 0, 1, 1, 0]
}

df2=pd.DataFrame(spam_data)
df2



,Email_Length,Contains_Link,Spam
0,50,0,0
1,75,0,0
2,100,1,1
3,120,1,1
4,60,0,0
5,150,1,1
6,80,0,0
7,180,1,1
8,90,1,1
9,70,0,0


# **Task 3: Model Training** 
1. Train Logistic Regression model  
2. Use fit()  
3. Predict outputs 

# pass/fail dataset

In [36]:
# Features and Label
X = df[['Study_Hours']]
y = df['Result']

# Create and train model
model = LogisticRegression()
#Use fit()
model.fit(X, y)

# Predict
predictions = model.predict(X)

print("Predictions:", predictions)

Predictions: [0 0 0 1 1 1 1 1]


# Disease Dataset

In [41]:
# Features and Label
A = df1[['Age', 'Sugar_Level']]
b = df1['Disease']

# Create and train model
model = LogisticRegression()
model.fit(A, b)

# Predict outputs
D_predict = model.predict(A)

print("Predictions:", D_predict)

Predictions: [0 0 0 0 1 1 1 1 1 1]


# Spam dataset

In [21]:
# Features and Label
M = df2[['Email_Length', 'Contains_Link']]
n = df2['Spam']

# Create and train model
model = LogisticRegression()
model.fit(M, n)

# Predict outputs
S_predictions = model.predict(M)

print("Predictions:", S_predictions)

Predictions: [0 0 1 1 0 1 0 1 1 0]


# **Task 4: Prediction Practice** 
1. Predict student result  
2. Predict disease status  
3. Predict spam message status 

In [37]:
# Predict student result
new_student = [[6]]  # 6 study hours

result = model.predict(new_student)

print("Predicted Result:", result)

Predicted Result: [1]


In [42]:
# Predict disease status
new_patient = [[42, 125]]  # Age, Sugar_Level

disease_status = model.predict(new_patient)

print("Disease Status:", disease_status)

Disease Status: [1]


In [22]:
# Predict spam message
new_email = [[110, 1]]  # Email_Length, Contains_Link

spam_status = model.predict(new_email)

print("Spam Status:", spam_status)

Spam Status: [1]


# **Task 5: Probability Analysis** 
1. Use predict_proba()  
2. Explain output  
3. Compare probabilities 

In [38]:
# Example: Predict probability for a new student
new_student = [[6]]

probabilities = model.predict_proba(new_student).round(2)

print(probabilities)

[[0.15 0.85]]


##### 2. Explain Output

The output contains probabilities for both classes:
| Class    | Probability |
| -------- | ----------- |
| 0 (Fail) | 0.15 (15%)  |
| 1 (Pass) | 0.85 (85%)  |
##### Interpretation:

* 15% chance the student will Fail
* 85% chance the student will Pass
* Since 85% is higher, the model predicts Pass (1)

In [43]:
#Disease Example
new_patient = [[42, 125]]

probabilities = model.predict_proba(new_patient)

print(probabilities)

[[0.00225984 0.99774016]]


In [44]:
#Spam example
new_email = [[110, 1]]

probabilities = model.predict_proba(new_email)

print(probabilities)

[[1.00000000e+00 1.95520532e-15]]


# **Task 6: Classification Logic**
For each problem identify whether Logistic Regression can be used: 
1. Pass/Fail Prediction  
2. House Price Prediction  
3. Spam Detection  
4. Disease Prediction  
5. Salary Prediction