**Task 2: Array Creation** 
1. Create 1D array  
2. Create 2D array  
3. Create 3D array  
4. Print all 

In [1]:
import numpy as np

In [8]:
#Create 1D Array
arr1=np.array([1,8,6,9])
print("1D Array:",arr1)

#create 2D Array
arr2=np.array([[1,3,6],[8,10,12]])
print("2D Array:",arr2)
#Create 3D Array
arr3=np.array([[[1,2],[3,4]]])
print("3D Array:",arr3)

1D Array: [1 8 6 9]
2D Array: [[ 1  3  6]
 [ 8 10 12]]
3D Array: [[[1 2]
  [3 4]]]


**Task 3: Properties**
1. Print shape  
2. Print dimensions  
3. Print data type  

In [16]:
#Print Shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(4,)
(2, 3)
(1, 2, 2)


In [19]:
#print dimensions
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [20]:
#print Datatypes
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
int64
int64


**Task 4: Special Arrays**
1. Create zero matrix  
2. Create ones matrix  
3. Create identity matrix  
4. Create range array  

In [24]:
#Create zero matrix
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
#create ones matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
#create identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
#create range array
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**Task 5: Indexing**
1. Access first element  
2. Slice array  
3. Access element in 2D 

In [29]:
arr = np.array([10, 20, 30, 40])

In [30]:
#Accessing first element
print("First element:", arr[0])

First element: 10


In [31]:
#Slice Array
print("Sliced array:", arr[1:3])

Sliced array: [20 30]


In [32]:
#Access element in 2D
arr2 = np.array([[1, 2], [3, 4]])

In [33]:
print("Element in 2D:", arr2[0, 1])

Element in 2D: 2


**Task 6: Reshaping** 
1. Convert 1D → 2D  
2. Convert 2D → 1D

In [34]:
#Convert 1D-> 2D
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr1.reshape(2, 3)
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [36]:
#Convert 2D->1D
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = arr2.flatten()
print(arr_1d)

[1 2 3 4 5 6]
