#  1. What is NumPy? 

NumPy (short for Numerical Python) is a powerful Python library used for working with numbers, arrays, and mathematical operations efficiently.
NumPy is a library that allows you to handle large amounts of numerical data using arrays instead of regular Python lists.

# Key Features
##### Provides multi-dimensional arrays (ndarray)
##### Performs fast mathematical calculations
##### Supports operations like sum, mean, matrix multiplication
##### Uses less memory and is faster than Python lists

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


# 2. Why NumPy is faster than lists?  

NumPy is faster than Python lists mainly because of how it stores and processes data internally.
###### 1. Contiguous Memory Storage
NumPy arrays store elements in a continuous block of memory, while Python lists store references (pointers) to objects.
➡️ This makes NumPy arrays:


Faster to access


More cache-friendly



###### 2. Fixed Data Type
In NumPy, all elements have the same data type, whereas Python lists can store mixed types.
➡️ Result:


No need to check data type for every element


Faster computations



###### 3. Vectorized Operations
NumPy performs operations on entire arrays at once instead of looping element by element.

➡️ No explicit loops → faster execution ⚡

###### 4. Uses Optimized C Code
NumPy is implemented using C and C++ under the hood, while Python lists rely on slower interpreted Python code.
➡️ Heavy calculations are executed at compiled speed

###### 5. Less Memory Usage
NumPy arrays use less memory compared to lists, which improves performance.



In [3]:
import numpy as np

a = np.array([1, 2, 3])
print(a * 2)   # Fast vectorized operation

[2 4 6]


# 3. What is array? 
An array is a data structure used to store multiple values of the same type in a single variable.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


#### Key Features of Arrays
###### Stores multiple elements in one variable
###### Elements are of the same data type
###### Allows fast access and operations
###### Can be 1D, 2D, or multi-dimensional

### Types of Arrays
###### 1D Array → [1, 2, 3]
###### 2D Array → [[1, 2], [3, 4]]
###### 3D Array → Collection of 2D arrays

# 4. What is shape and dimension? 

These are two important properties of a NumPy array that describe its structure.

# 1. Dimension (ndim)

###### Dimension refers to the number of axes (directions) in an array.

###### 1D array → 1 dimension
###### 2D array → 2 dimensions (rows & columns)
###### 3D array → 3 dimensions

In [6]:
arr = np.array([[1, 2], [3, 4]])
print(arr.ndim)   

2


# 2. Shape (shape)

Shape tells how many elements are present in each dimension.

# 5. What is reshaping? 

Reshaping means changing the shape (structure) of an array without changing its data.

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]
