**Basic Aggregation** 
1. Find sum  
2. Find mean  
3. Find max and min 

In [1]:
import numpy as np

In [2]:
arr=np.array([5,4,8,7,10,6,2])

In [5]:
print("Sum:",np.sum(arr))  #sum
print("Mean:",np.mean(arr)) #mean
print("Max:",np.max(arr),"Min:",np.min(arr))  #max and min

Sum: 42
Mean: 6.0
Max: 10 Min: 2


**Task 3: Statistical Functions** 
1. Find median  
2. Find standard deviation  
3. Find variance 

In [9]:
print("Median:",np.median(arr))  #median
print("Standard deviation:",round(np.std(arr),2)) #standard deviation
print("Variance:",np.var(arr))  #varience

Median: 6.0
Standard deviation: 2.45
Variance: 6.0


**Task 4: Axis Practice** 
1. Row-wise sum  
2. Column-wise sum  
3. Mean using axis 

In [19]:
arr1 = np.array([[2,4,6],
               [8,10,12]])
print(arr1)

[[ 2  4  6]
 [ 8 10 12]]


In [20]:
print("Row-wise sum:",np.sum(arr1,axis=1)) #row wise sum
print("Column-wise sum:",np.sum(arr1,axis=0)) #Column wise sum
print("Mean using axis:",np.mean(arr1,axis=1))
print("Mean using axis:",np.mean(arr1,axis=0))

Row-wise sum: [12 30]
Column-wise sum: [10 14 18]
Mean using axis: [ 4. 10.]
Mean using axis: [5. 7. 9.]


**Task 5: Index Functions** 
1. Find index of max  
2. Find index of min 

In [24]:
arr=np.array([5,4,8,7,10,6,2])
print("Index of max:",np.argmax(arr)) #Index of max
print("Index of min:",np.argmin(arr)) #Index of min

Index of max: 4
Index of min: 6


**Task 6: Cumulative** 
1. Compute cumulative sum  
2. Analyze output

In [25]:
arr=np.array([5,4,8,7,10,6,2])
print(np.cumsum(arr))  #cumilative sum

[ 5  9 17 24 34 40 42]


###### output analysis
###### step 1-  5  
###### step 2= 5+4 = 9  # current elemet + previous element
###### step 3 = 9+8 =17
###### step 4= 17+7= 24
###### step 5= 24+10 = 34
###### step 6=34 + 6 =40
###### step7= 40+2 = 42