In [3]:
import numpy as np

**Task 2: Basic Broadcasting** 
1. Add scalar to array  
2. Multiply array with scalar  
3. Divide array by scalar  

In [4]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [7]:
#Add scalar to array
print(arr+5)
print(arr*2)
print(arr / 5)

[15 25 35 45 55]
[ 20  40  60  80 100]
[ 2.  4.  6.  8. 10.]


**Task 3: Array Broadcasting** 
1. Add two compatible arrays  
2. Multiply arrays  
3. Observe shape changes  

In [8]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

In [13]:
print("Add two compatible array:",a+b)
print("Multiply arrays:",a*b)
print("Observe shape changes")
print(a.shape)
print(b.shape)

Add two compatible array: [[11 22 33]
 [14 25 36]]
Multiply arrays: [[ 10  40  90]
 [ 40 100 180]]
Observe shape changes
(2, 3)
(3,)


**Task 4: Shape Practice** 
1. Print shapes  
2. Check compatible shapes  
3. Try incompatible shapes 

In [14]:
#print shapes

a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

print(a.shape)
print(b.shape)

(2, 3)
(3,)


In [16]:
#Check compatible shapes


b = np.array([10,20,30])

print(a + b)   # compatible because dimensions are equal

[[11 22 33]
 [14 25 36]]


In [17]:
# try incompatibe shapes
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20])

print(a + b)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

**Task 5: 2D Broadcasting** 
1. Add scalar to matrix  
2. Multiply matrix  
3. Normalize matrix values 

In [18]:
#Add scalar to matrix
matrix = np.array([[1,2,3],
                   [4,5,6]])

print(matrix + 10)

[[11 12 13]
 [14 15 16]]


In [19]:
#Multyply matrix
print(matrix * 5)

[[ 5 10 15]
 [20 25 30]]


In [21]:
#Normalize matrix values
print(matrix / 60)   #To normalice matrix divided by maximum value 60. values between 0 and 1

[[0.01666667 0.03333333 0.05      ]
 [0.06666667 0.08333333 0.1       ]]
