**Task 2: Random Integer Practice** 
1. Generate random integer  
2. Generate array of integers  
3. Create random matrix  

In [1]:
import numpy as np

In [9]:
#generate random integer
print(np.random.randint(1,50))
#generate array of integers
print(np.random.randint(1,50,size=5))
#generate random matrix
print(np.random.randint(1,100,size=(3,3)))

39
[17 31 38  9 47]
[[24 63 45]
 [39 70 69]
 [91 17 64]]


**Task 3: Random Decimal Practice** 
1. Generate decimal values  
2. Create 2D decimal matrix 

In [17]:
#generate decimal values
print(np.random.rand(10))
#create 2D decimal matrix
print( np.random.rand(3, 3))

[0.6528774  0.07807154 0.97708524 0.41136337 0.86513054 0.21549656
 0.02995946 0.09670326 0.39033898 0.70458502]
[[0.85662999 0.62509453 0.93940535]
 [0.7040559  0.8865327  0.78150215]
 [0.86714947 0.82384839 0.90938543]]


**Task 4: Random Choice** 
1. Pick random color  
2. Generate multiple choices  
3. Simulate random names 

In [18]:
#Pick random color
colors = ["Red", "Blue", "Green", "Yellow"]
print(np.random.choice(colors))

Red


In [19]:
#Generate multiple choices
numbers = [1, 2, 3, 4, 5]

choices = np.random.choice(numbers, size=3)

print(choices)

[2 2 4]


In [20]:
#simulate random names
names = ["Arun", "Meera", "Rahul", "Anu", "Kiran"]

random_names = np.random.choice(names, size=3)

print(random_names)

['Arun' 'Rahul' 'Anu']


**Task 5: Shuffle** 
1. Shuffle array  
2. Shuffle student IDs 

In [21]:
#Shuffle array
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[5 2 1 3 4]


In [22]:
#Shuffle student IDs
student_ids = np.array([101, 102, 103, 104, 105])
np.random.shuffle(student_ids)
print(student_ids)

[102 101 103 104 105]


**Task 6: Dataset Simulation** 
1. Create marks dataset  
2. Create attendance dataset  
3. Create random image matrix

In [23]:
#Create marks dataset
marks = np.random.randint(40, 101, size=10)
print(marks)

[100  58  50  73 100  47  42  69  58  84]


In [24]:
#Create attendance dataset
attendance = np.random.randint(60, 101, size=10)
print(attendance)

[67 90 93 66 74 64 60 66 66 71]


In [25]:
#create random image matrix
import numpy as np

image = np.random.randint(0, 256, size=(5,3))

print(image)

[[203 254 101]
 [239 148  59]
 [149 109 116]
 [175   4 184]
 [ 58  24 132]]
