**Task 2: Marks Analysis**
1. Find average marks  
2. Find highest marks  
3. Find lowest marks  
4. Find topper 

In [1]:
import numpy as np

In [6]:
students = np.array(["Anuja", "Ram", "Meera", "Arjun", "Diya"])
marks = np.array([78, 92, 85, 96, 88])

print("Average marks:",np.mean(marks))
print("Highest marks:",np.max(marks))
print("Lowest marks:",np.min(marks))
topper=np.argmax(marks)
print("Find topper:",students[topper])


Average marks: 87.8
Highest marks: 96
Lowest marks: 78
Find topper: Arjun


**Task 3: Image Operations**
1. Increase brightness  
2. Decrease brightness  
3. Normalize image pixels  

In [7]:
image = np.array([[50, 100, 150],
                  [200, 250, 180],
                  [90, 60, 30]])
print(image)

[[ 50 100 150]
 [200 250 180]
 [ 90  60  30]]


In [10]:
#Increase brightness
bright_image = image + 50
print(bright_image)

[[100 150 200]
 [250 300 230]
 [140 110  80]]


In [11]:
#Dcrease brightness
decrease_image = image-50
print(decrease_image)

[[  0  50 100]
 [150 200 130]
 [ 40  10 -20]]


In [12]:
# Normalize image pixels
normalized_image = image / 255
print(normalized_image)

[[0.19607843 0.39215686 0.58823529]
 [0.78431373 0.98039216 0.70588235]
 [0.35294118 0.23529412 0.11764706]]


**Task 4: Dataset Filtering**
1. Filter values > 50  
2. Replace low values  
3. Count filtered values 

In [13]:
data = np.array([23, 67, 45, 89, 12, 76, 54, 30, 95])

In [25]:
print("Filterd values:",data[data > 50])
data[data<50]=0
print("Replace low values:",data )
filtered_values = data[data > 50]
count_values = np.sum(filtered_values > 50)
print("\nCount of Values Greater Than 50:", count_values)

Filterd values: [67 89 76 54 95]
Replace low values: [ 0 67  0 89  0 76 54  0 95]

Count of Values Greater Than 50: 5


**Task 5: Reshaping**
1. Convert 1D → 2D  
2. Convert 2D → 1D  
3. Create 3D dataset 

In [27]:
#Convert 1D -> 2D
arr1d = np.array([1, 2, 3, 4, 5, 6])
arr2d = arr1d.reshape(2, 3)
print("1D Array:")
print(arr1d)
print("\nConverted to 2D Array:")
print(arr2d)
# Convert 2D → 1D
back_to_1d = arr2d.flatten()
print("\nConverted Back to 1D:")
print(back_to_1d)
# 3. Create 3D dataset
dataset_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("\n3D Dataset:")
print(dataset_3d)

1D Array:
[1 2 3 4 5 6]

Converted to 2D Array:
[[1 2 3]
 [4 5 6]]

Converted Back to 1D:
[1 2 3 4 5 6]

3D Dataset:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Task 6: Dataset Simulation** 
1. Attendance matrix  
2. Marks dataset  
3. Weather dataset 